version: "3"

services:
  mysql:
    image: mysql
    ports:
      - "3308:3306" # External port 3308 mapped to internal port 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 20s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./BE
    volumes:
      - ./BE:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - ./BE/config.env
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./FE
    volumes:
      - ./FE:/app
      - /app/node_modules
    ports:
      # - "5173:5173"
      # ports:
      - "80:80"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mysql-data:
